// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CROSSNAMESPACEPACKTEST_FOO_H_
#define FLATBUFFERS_GENERATED_CROSSNAMESPACEPACKTEST_FOO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 0 &&
              FLATBUFFERS_VERSION_MINOR == 5,
             "Non-compatible flatbuffers version included");

namespace native {

struct TableWithNative;
struct TableWithNativeBuilder;
struct TableWithNativeT;

}  // namespace native

namespace foo {

struct Consumer;
struct ConsumerBuilder;
struct ConsumerT;

}  // namespace foo

namespace native {

bool operator==(const TableWithNativeT &lhs, const TableWithNativeT &rhs);
bool operator!=(const TableWithNativeT &lhs, const TableWithNativeT &rhs);
}  // namespace native

namespace foo {

bool operator==(const ConsumerT &lhs, const ConsumerT &rhs);
bool operator!=(const ConsumerT &lhs, const ConsumerT &rhs);

}  // namespace foo

namespace native {

inline const ::flatbuffers::TypeTable *TableWithNativeTypeTable();

}  // namespace native

namespace foo {

inline const ::flatbuffers::TypeTable *ConsumerTypeTable();

}  // namespace foo

namespace native {

struct TableWithNativeT : public ::flatbuffers::NativeTable {
  typedef TableWithNative TableType;
  int32_t value = 0;
};

struct TableWithNative FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TableWithNativeT NativeTableType;
  typedef TableWithNativeBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TableWithNativeTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool mutate_value(int32_t _value = 0) {
    return SetField<int32_t>(VT_VALUE, _value, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
  TableWithNativeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TableWithNativeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TableWithNative> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TableWithNativeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TableWithNativeBuilder {
  typedef TableWithNative Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(TableWithNative::VT_VALUE, value, 0);
  }
  explicit TableWithNativeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TableWithNative> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TableWithNative>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TableWithNative> CreateTableWithNative(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t value = 0) {
  TableWithNativeBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

::flatbuffers::Offset<TableWithNative> CreateTableWithNative(::flatbuffers::FlatBufferBuilder &_fbb, const TableWithNativeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace native

namespace foo {

struct ConsumerT : public ::flatbuffers::NativeTable {
  typedef Consumer TableType;
  std::unique_ptr<native::TableWithNativeT> c1{};
  std::vector<std::unique_ptr<native::TableWithNativeT>> c2{};
  ConsumerT() = default;
  ConsumerT(const ConsumerT &o);
  ConsumerT(ConsumerT&&) FLATBUFFERS_NOEXCEPT = default;
  ConsumerT &operator=(ConsumerT o) FLATBUFFERS_NOEXCEPT;
};

struct Consumer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConsumerT NativeTableType;
  typedef ConsumerBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConsumerTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_C1 = 4,
    VT_C2 = 6
  };
  const native::TableWithNative *c1() const {
    return GetPointer<const native::TableWithNative *>(VT_C1);
  }
  native::TableWithNative *mutable_c1() {
    return GetPointer<native::TableWithNative *>(VT_C1);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>> *c2() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>> *>(VT_C2);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>> *mutable_c2() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>> *>(VT_C2);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_C1) &&
           verifier.VerifyTable(c1()) &&
           VerifyOffset(verifier, VT_C2) &&
           verifier.VerifyVector(c2()) &&
           verifier.VerifyVectorOfTables(c2()) &&
           verifier.EndTable();
  }
  ConsumerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConsumerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Consumer> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConsumerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConsumerBuilder {
  typedef Consumer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_c1(::flatbuffers::Offset<native::TableWithNative> c1) {
    fbb_.AddOffset(Consumer::VT_C1, c1);
  }
  void add_c2(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>>> c2) {
    fbb_.AddOffset(Consumer::VT_C2, c2);
  }
  explicit ConsumerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Consumer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Consumer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Consumer> CreateConsumer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<native::TableWithNative> c1 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<native::TableWithNative>>> c2 = 0) {
  ConsumerBuilder builder_(_fbb);
  builder_.add_c2(c2);
  builder_.add_c1(c1);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Consumer> CreateConsumerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<native::TableWithNative> c1 = 0,
    const std::vector<::flatbuffers::Offset<native::TableWithNative>> *c2 = nullptr) {
  auto c2__ = c2 ? _fbb.CreateVector<::flatbuffers::Offset<native::TableWithNative>>(*c2) : 0;
  return foo::CreateConsumer(
      _fbb,
      c1,
      c2__);
}

::flatbuffers::Offset<Consumer> CreateConsumer(::flatbuffers::FlatBufferBuilder &_fbb, const ConsumerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace foo

namespace native {


inline bool operator==(const TableWithNativeT &lhs, const TableWithNativeT &rhs) {
  return
      (lhs.value == rhs.value);
}

inline bool operator!=(const TableWithNativeT &lhs, const TableWithNativeT &rhs) {
    return !(lhs == rhs);
}


inline TableWithNativeT *TableWithNative::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TableWithNativeT>(new TableWithNativeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TableWithNative::UnPackTo(TableWithNativeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<TableWithNative> CreateTableWithNative(::flatbuffers::FlatBufferBuilder &_fbb, const TableWithNativeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TableWithNative::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TableWithNative> TableWithNative::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TableWithNativeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TableWithNativeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _value = _o->value;
  return native::CreateTableWithNative(
      _fbb,
      _value);
}

}  // namespace native

namespace foo {


inline bool operator==(const ConsumerT &lhs, const ConsumerT &rhs) {
  return
      ((lhs.c1 == rhs.c1) || (lhs.c1 && rhs.c1 && *lhs.c1 == *rhs.c1)) &&
      (lhs.c2.size() == rhs.c2.size() && std::equal(lhs.c2.cbegin(), lhs.c2.cend(), rhs.c2.cbegin(), [](std::unique_ptr<native::TableWithNativeT> const &a, std::unique_ptr<native::TableWithNativeT> const &b) { return (a == b) || (a && b && *a == *b); }));
}

inline bool operator!=(const ConsumerT &lhs, const ConsumerT &rhs) {
    return !(lhs == rhs);
}


inline ConsumerT::ConsumerT(const ConsumerT &o)
      : c1((o.c1) ? new native::TableWithNativeT(*o.c1) : nullptr) {
  c2.reserve(o.c2.size());
  for (const auto &c2_ : o.c2) { c2.emplace_back((c2_) ? new native::TableWithNativeT(*c2_) : nullptr); }
}

inline ConsumerT &ConsumerT::operator=(ConsumerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(c1, o.c1);
  std::swap(c2, o.c2);
  return *this;
}

inline ConsumerT *Consumer::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ConsumerT>(new ConsumerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Consumer::UnPackTo(ConsumerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = c1(); if (_e) { if(_o->c1) { _e->UnPackTo(_o->c1.get(), _resolver); } else { _o->c1 = std::unique_ptr<native::TableWithNativeT>(_e->UnPack(_resolver)); } } else if (_o->c1) { _o->c1.reset(); } }
  { auto _e = c2(); if (_e) { _o->c2.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->c2[_i]) { _e->Get(_i)->UnPackTo(_o->c2[_i].get(), _resolver); } else { _o->c2[_i] = std::unique_ptr<native::TableWithNativeT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->c2.resize(0); } }
}

inline ::flatbuffers::Offset<Consumer> CreateConsumer(::flatbuffers::FlatBufferBuilder &_fbb, const ConsumerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Consumer::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Consumer> Consumer::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConsumerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConsumerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _c1 = _o->c1 ? native::CreateTableWithNative(_fbb, _o->c1.get(), _rehasher) : 0;
  auto _c2 = _o->c2.size() ? _fbb.CreateVector<::flatbuffers::Offset<native::TableWithNative>> (_o->c2.size(), [](size_t i, _VectorArgs *__va) { return native::CreateTableWithNative(*__va->__fbb, __va->__o->c2[i].get(), __va->__rehasher); }, &_va ) : 0;
  return foo::CreateConsumer(
      _fbb,
      _c1,
      _c2);
}

}  // namespace foo

namespace native {

inline const ::flatbuffers::TypeTable *TableWithNativeTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 }
  };
  static const char * const names[] = {
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

}  // namespace native

namespace foo {

inline const ::flatbuffers::TypeTable *ConsumerTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    native::TableWithNativeTypeTable
  };
  static const char * const names[] = {
    "c1",
    "c2"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const foo::Consumer *GetConsumer(const void *buf) {
  return ::flatbuffers::GetRoot<foo::Consumer>(buf);
}

inline const foo::Consumer *GetSizePrefixedConsumer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foo::Consumer>(buf);
}

inline Consumer *GetMutableConsumer(void *buf) {
  return ::flatbuffers::GetMutableRoot<Consumer>(buf);
}

inline foo::Consumer *GetMutableSizePrefixedConsumer(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<foo::Consumer>(buf);
}

template <bool B = false>
inline bool VerifyConsumerBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<foo::Consumer>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedConsumerBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<foo::Consumer>(nullptr);
}

inline void FinishConsumerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foo::Consumer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedConsumerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foo::Consumer> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<foo::ConsumerT> UnPackConsumer(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<foo::ConsumerT>(GetConsumer(buf)->UnPack(res));
}

inline std::unique_ptr<foo::ConsumerT> UnPackSizePrefixedConsumer(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<foo::ConsumerT>(GetSizePrefixedConsumer(buf)->UnPack(res));
}

}  // namespace foo

#endif  // FLATBUFFERS_GENERATED_CROSSNAMESPACEPACKTEST_FOO_H_
