// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAPSETTEST_MAPSETTEST_H_
#define FLATBUFFERS_GENERATED_MAPSETTEST_MAPSETTEST_H_

#include "flatbuffers/flatbuffers.h"
#include <algorithm>
#include <unordered_map>
#include <unordered_set>

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 0 &&
              FLATBUFFERS_VERSION_MINOR == 5,
             "Non-compatible flatbuffers version included");

namespace MapSetTest {

struct Stats;
struct StatsBuilder;
struct StatsT;

struct Config;
struct ConfigBuilder;
struct ConfigT;

struct __Map_string_int_Entry;
struct __Map_string_int_EntryBuilder;
struct __Map_string_int_EntryT;

struct __Map_uint_string_Entry;
struct __Map_uint_string_EntryBuilder;
struct __Map_uint_string_EntryT;

struct __Map_Color_float_Entry;
struct __Map_Color_float_EntryBuilder;
struct __Map_Color_float_EntryT;

struct __Map_string_Stats_Entry;
struct __Map_string_Stats_EntryBuilder;
struct __Map_string_Stats_EntryT;

struct __Set_string_Entry;
struct __Set_string_EntryBuilder;
struct __Set_string_EntryT;

struct __Set_int_Entry;
struct __Set_int_EntryBuilder;
struct __Set_int_EntryT;

struct AnotherConfig;
struct AnotherConfigBuilder;
struct AnotherConfigT;

bool operator==(const StatsT &lhs, const StatsT &rhs);
bool operator!=(const StatsT &lhs, const StatsT &rhs);
bool operator==(const ConfigT &lhs, const ConfigT &rhs);
bool operator!=(const ConfigT &lhs, const ConfigT &rhs);
bool operator==(const __Map_string_int_EntryT &lhs, const __Map_string_int_EntryT &rhs);
bool operator!=(const __Map_string_int_EntryT &lhs, const __Map_string_int_EntryT &rhs);
bool operator==(const __Map_uint_string_EntryT &lhs, const __Map_uint_string_EntryT &rhs);
bool operator!=(const __Map_uint_string_EntryT &lhs, const __Map_uint_string_EntryT &rhs);
bool operator==(const __Map_Color_float_EntryT &lhs, const __Map_Color_float_EntryT &rhs);
bool operator!=(const __Map_Color_float_EntryT &lhs, const __Map_Color_float_EntryT &rhs);
bool operator==(const __Map_string_Stats_EntryT &lhs, const __Map_string_Stats_EntryT &rhs);
bool operator!=(const __Map_string_Stats_EntryT &lhs, const __Map_string_Stats_EntryT &rhs);
bool operator==(const __Set_string_EntryT &lhs, const __Set_string_EntryT &rhs);
bool operator!=(const __Set_string_EntryT &lhs, const __Set_string_EntryT &rhs);
bool operator==(const __Set_int_EntryT &lhs, const __Set_int_EntryT &rhs);
bool operator!=(const __Set_int_EntryT &lhs, const __Set_int_EntryT &rhs);
bool operator==(const AnotherConfigT &lhs, const AnotherConfigT &rhs);
bool operator!=(const AnotherConfigT &lhs, const AnotherConfigT &rhs);

inline const ::flatbuffers::TypeTable *StatsTypeTable();

inline const ::flatbuffers::TypeTable *ConfigTypeTable();

inline const ::flatbuffers::TypeTable *__Map_string_int_EntryTypeTable();

inline const ::flatbuffers::TypeTable *__Map_uint_string_EntryTypeTable();

inline const ::flatbuffers::TypeTable *__Map_Color_float_EntryTypeTable();

inline const ::flatbuffers::TypeTable *__Map_string_Stats_EntryTypeTable();

inline const ::flatbuffers::TypeTable *__Set_string_EntryTypeTable();

inline const ::flatbuffers::TypeTable *__Set_int_EntryTypeTable();

inline const ::flatbuffers::TypeTable *AnotherConfigTypeTable();

enum Color : int8_t {
  Color_Red = 0,
  Color_Green = 1,
  Color_Blue = 2,
  Color_MIN = Color_Red,
  Color_MAX = Color_Blue
};

inline const Color (&EnumValuesColor())[3] {
  static const Color values[] = {
    Color_Red,
    Color_Green,
    Color_Blue
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[4] = {
    "Red",
    "Green",
    "Blue",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (::flatbuffers::IsOutRange(e, Color_Red, Color_Blue)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

struct StatsT : public ::flatbuffers::NativeTable {
  typedef Stats TableType;
  int32_t hp = 0;
  float strength = 0.0f;
};

struct Stats FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatsT NativeTableType;
  typedef StatsBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return StatsTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HP = 4,
    VT_STRENGTH = 6
  };
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  bool mutate_hp(int32_t _hp = 0) {
    return SetField<int32_t>(VT_HP, _hp, 0);
  }
  float strength() const {
    return GetField<float>(VT_STRENGTH, 0.0f);
  }
  bool mutate_strength(float _strength = 0.0f) {
    return SetField<float>(VT_STRENGTH, _strength, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_HP, 4) &&
           VerifyField<float>(verifier, VT_STRENGTH, 4) &&
           verifier.EndTable();
  }
  StatsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(StatsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Stats> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StatsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct StatsBuilder {
  typedef Stats Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(Stats::VT_HP, hp, 0);
  }
  void add_strength(float strength) {
    fbb_.AddElement<float>(Stats::VT_STRENGTH, strength, 0.0f);
  }
  explicit StatsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Stats> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Stats>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Stats> CreateStats(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t hp = 0,
    float strength = 0.0f) {
  StatsBuilder builder_(_fbb);
  builder_.add_strength(strength);
  builder_.add_hp(hp);
  return builder_.Finish();
}

::flatbuffers::Offset<Stats> CreateStats(::flatbuffers::FlatBufferBuilder &_fbb, const StatsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ConfigT : public ::flatbuffers::NativeTable {
  typedef Config TableType;
  std::unordered_map<std::string, int32_t> settings{};
  std::unordered_map<uint32_t, std::string> id_to_name{};
  std::unordered_map<MapSetTest::Color, float> color_scores{};
  std::unordered_map<std::string, std::unique_ptr<MapSetTest::StatsT>> profiles{};
  std::unordered_set<std::string> tags{};
  std::unordered_set<int32_t> active_ids{};
  ConfigT() = default;
  ConfigT(const ConfigT &o);
  ConfigT(ConfigT&&) FLATBUFFERS_NOEXCEPT = default;
  ConfigT &operator=(ConfigT o) FLATBUFFERS_NOEXCEPT;
};

struct Config FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConfigT NativeTableType;
  typedef ConfigBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return ConfigTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SETTINGS = 4,
    VT_ID_TO_NAME = 6,
    VT_COLOR_SCORES = 8,
    VT_PROFILES = 10,
    VT_TAGS = 12,
    VT_ACTIVE_IDS = 14
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *settings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *>(VT_SETTINGS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *mutable_settings() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *>(VT_SETTINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> *id_to_name() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> *>(VT_ID_TO_NAME);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> *mutable_id_to_name() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> *>(VT_ID_TO_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> *color_scores() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> *>(VT_COLOR_SCORES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> *mutable_color_scores() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> *>(VT_COLOR_SCORES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> *profiles() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> *>(VT_PROFILES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> *mutable_profiles() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> *>(VT_PROFILES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *>(VT_TAGS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *mutable_tags() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *>(VT_TAGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> *active_ids() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> *>(VT_ACTIVE_IDS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> *mutable_active_ids() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> *>(VT_ACTIVE_IDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SETTINGS) &&
           verifier.VerifyVector(settings()) &&
           verifier.VerifyVectorOfTables(settings()) &&
           VerifyOffset(verifier, VT_ID_TO_NAME) &&
           verifier.VerifyVector(id_to_name()) &&
           verifier.VerifyVectorOfTables(id_to_name()) &&
           VerifyOffset(verifier, VT_COLOR_SCORES) &&
           verifier.VerifyVector(color_scores()) &&
           verifier.VerifyVectorOfTables(color_scores()) &&
           VerifyOffset(verifier, VT_PROFILES) &&
           verifier.VerifyVector(profiles()) &&
           verifier.VerifyVectorOfTables(profiles()) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfTables(tags()) &&
           VerifyOffset(verifier, VT_ACTIVE_IDS) &&
           verifier.VerifyVector(active_ids()) &&
           verifier.VerifyVectorOfTables(active_ids()) &&
           verifier.EndTable();
  }
  ConfigT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Config> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConfigBuilder {
  typedef Config Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_settings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>>> settings) {
    fbb_.AddOffset(Config::VT_SETTINGS, settings);
  }
  void add_id_to_name(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>>> id_to_name) {
    fbb_.AddOffset(Config::VT_ID_TO_NAME, id_to_name);
  }
  void add_color_scores(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>>> color_scores) {
    fbb_.AddOffset(Config::VT_COLOR_SCORES, color_scores);
  }
  void add_profiles(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>>> profiles) {
    fbb_.AddOffset(Config::VT_PROFILES, profiles);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>>> tags) {
    fbb_.AddOffset(Config::VT_TAGS, tags);
  }
  void add_active_ids(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>>> active_ids) {
    fbb_.AddOffset(Config::VT_ACTIVE_IDS, active_ids);
  }
  explicit ConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Config> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Config>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Config> CreateConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>>> settings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>>> id_to_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>>> color_scores = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>>> profiles = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>>> tags = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>>> active_ids = 0) {
  ConfigBuilder builder_(_fbb);
  builder_.add_active_ids(active_ids);
  builder_.add_tags(tags);
  builder_.add_profiles(profiles);
  builder_.add_color_scores(color_scores);
  builder_.add_id_to_name(id_to_name);
  builder_.add_settings(settings);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Config> CreateConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *settings = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> *id_to_name = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> *color_scores = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> *profiles = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *tags = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> *active_ids = nullptr) {
  auto settings__ = settings ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Map_string_int_Entry>(settings) : 0;
  auto id_to_name__ = id_to_name ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Map_uint_string_Entry>(id_to_name) : 0;
  auto color_scores__ = color_scores ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Map_Color_float_Entry>(color_scores) : 0;
  auto profiles__ = profiles ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Map_string_Stats_Entry>(profiles) : 0;
  auto tags__ = tags ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Set_string_Entry>(tags) : 0;
  auto active_ids__ = active_ids ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Set_int_Entry>(active_ids) : 0;
  return MapSetTest::CreateConfig(
      _fbb,
      settings__,
      id_to_name__,
      color_scores__,
      profiles__,
      tags__,
      active_ids__);
}

::flatbuffers::Offset<Config> CreateConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Map_string_int_EntryT : public ::flatbuffers::NativeTable {
  typedef __Map_string_int_Entry TableType;
  std::string key{};
  int32_t value = 0;
};

struct __Map_string_int_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Map_string_int_EntryT NativeTableType;
  typedef __Map_string_int_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Map_string_int_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  ::flatbuffers::String *mutable_key() {
    return GetPointer<::flatbuffers::String *>(VT_KEY);
  }
  bool KeyCompareLessThan(const __Map_string_int_Entry * const o) const {
    return *key() < *o->key();
  }
  int KeyCompareWithValue(const char *_key) const {
    return strcmp(key()->c_str(), _key);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _key) const {
    if (key()->c_str() < _key) return -1;
    if (_key < key()->c_str()) return 1;
    return 0;
  }
  int32_t value() const {
    return GetField<int32_t>(VT_VALUE, 0);
  }
  bool mutate_value(int32_t _value = 0) {
    return SetField<int32_t>(VT_VALUE, _value, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<int32_t>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
  __Map_string_int_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Map_string_int_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Map_string_int_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_int_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Map_string_int_EntryBuilder {
  typedef __Map_string_int_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(__Map_string_int_Entry::VT_KEY, key);
  }
  void add_value(int32_t value) {
    fbb_.AddElement<int32_t>(__Map_string_int_Entry::VT_VALUE, value, 0);
  }
  explicit __Map_string_int_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Map_string_int_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Map_string_int_Entry>(end);
    fbb_.Required(o, __Map_string_int_Entry::VT_KEY);
    return o;
  }
};

inline ::flatbuffers::Offset<__Map_string_int_Entry> Create__Map_string_int_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    int32_t value = 0) {
  __Map_string_int_EntryBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<__Map_string_int_Entry> Create__Map_string_int_EntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    int32_t value = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return MapSetTest::Create__Map_string_int_Entry(
      _fbb,
      key__,
      value);
}

::flatbuffers::Offset<__Map_string_int_Entry> Create__Map_string_int_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_int_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Map_uint_string_EntryT : public ::flatbuffers::NativeTable {
  typedef __Map_uint_string_Entry TableType;
  uint32_t key = 0;
  std::string value{};
};

struct __Map_uint_string_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Map_uint_string_EntryT NativeTableType;
  typedef __Map_uint_string_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Map_uint_string_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  uint32_t key() const {
    return GetField<uint32_t>(VT_KEY, 0);
  }
  bool mutate_key(uint32_t _key = 0) {
    return SetField<uint32_t>(VT_KEY, _key, 0);
  }
  bool KeyCompareLessThan(const __Map_uint_string_Entry * const o) const {
    return key() < o->key();
  }
  int KeyCompareWithValue(uint32_t _key) const {
    return static_cast<int>(key() > _key) - static_cast<int>(key() < _key);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  ::flatbuffers::String *mutable_value() {
    return GetPointer<::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_KEY, 4) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
  __Map_uint_string_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Map_uint_string_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Map_uint_string_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_uint_string_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Map_uint_string_EntryBuilder {
  typedef __Map_uint_string_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(uint32_t key) {
    fbb_.AddElement<uint32_t>(__Map_uint_string_Entry::VT_KEY, key, 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(__Map_uint_string_Entry::VT_VALUE, value);
  }
  explicit __Map_uint_string_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Map_uint_string_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Map_uint_string_Entry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<__Map_uint_string_Entry> Create__Map_uint_string_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  __Map_uint_string_EntryBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<__Map_uint_string_Entry> Create__Map_uint_string_EntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t key = 0,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return MapSetTest::Create__Map_uint_string_Entry(
      _fbb,
      key,
      value__);
}

::flatbuffers::Offset<__Map_uint_string_Entry> Create__Map_uint_string_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_uint_string_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Map_Color_float_EntryT : public ::flatbuffers::NativeTable {
  typedef __Map_Color_float_Entry TableType;
  MapSetTest::Color key = MapSetTest::Color_Red;
  float value = 0.0f;
};

struct __Map_Color_float_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Map_Color_float_EntryT NativeTableType;
  typedef __Map_Color_float_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Map_Color_float_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  MapSetTest::Color key() const {
    return static_cast<MapSetTest::Color>(GetField<int8_t>(VT_KEY, 0));
  }
  bool mutate_key(MapSetTest::Color _key = static_cast<MapSetTest::Color>(0)) {
    return SetField<int8_t>(VT_KEY, static_cast<int8_t>(_key), 0);
  }
  bool KeyCompareLessThan(const __Map_Color_float_Entry * const o) const {
    return key() < o->key();
  }
  int KeyCompareWithValue(int8_t _key) const {
    return static_cast<int>(key() > _key) - static_cast<int>(key() < _key);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool mutate_value(float _value = 0.0f) {
    return SetField<float>(VT_VALUE, _value, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KEY, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
  __Map_Color_float_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Map_Color_float_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Map_Color_float_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_Color_float_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Map_Color_float_EntryBuilder {
  typedef __Map_Color_float_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(MapSetTest::Color key) {
    fbb_.AddElement<int8_t>(__Map_Color_float_Entry::VT_KEY, static_cast<int8_t>(key), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(__Map_Color_float_Entry::VT_VALUE, value, 0.0f);
  }
  explicit __Map_Color_float_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Map_Color_float_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Map_Color_float_Entry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<__Map_Color_float_Entry> Create__Map_Color_float_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MapSetTest::Color key = MapSetTest::Color_Red,
    float value = 0.0f) {
  __Map_Color_float_EntryBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

::flatbuffers::Offset<__Map_Color_float_Entry> Create__Map_Color_float_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_Color_float_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Map_string_Stats_EntryT : public ::flatbuffers::NativeTable {
  typedef __Map_string_Stats_Entry TableType;
  std::string key{};
  std::unique_ptr<MapSetTest::StatsT> value{};
  __Map_string_Stats_EntryT() = default;
  __Map_string_Stats_EntryT(const __Map_string_Stats_EntryT &o);
  __Map_string_Stats_EntryT(__Map_string_Stats_EntryT&&) FLATBUFFERS_NOEXCEPT = default;
  __Map_string_Stats_EntryT &operator=(__Map_string_Stats_EntryT o) FLATBUFFERS_NOEXCEPT;
};

struct __Map_string_Stats_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Map_string_Stats_EntryT NativeTableType;
  typedef __Map_string_Stats_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Map_string_Stats_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  ::flatbuffers::String *mutable_key() {
    return GetPointer<::flatbuffers::String *>(VT_KEY);
  }
  bool KeyCompareLessThan(const __Map_string_Stats_Entry * const o) const {
    return *key() < *o->key();
  }
  int KeyCompareWithValue(const char *_key) const {
    return strcmp(key()->c_str(), _key);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _key) const {
    if (key()->c_str() < _key) return -1;
    if (_key < key()->c_str()) return 1;
    return 0;
  }
  const MapSetTest::Stats *value() const {
    return GetPointer<const MapSetTest::Stats *>(VT_VALUE);
  }
  MapSetTest::Stats *mutable_value() {
    return GetPointer<MapSetTest::Stats *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
  __Map_string_Stats_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Map_string_Stats_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Map_string_Stats_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_Stats_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Map_string_Stats_EntryBuilder {
  typedef __Map_string_Stats_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(__Map_string_Stats_Entry::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<MapSetTest::Stats> value) {
    fbb_.AddOffset(__Map_string_Stats_Entry::VT_VALUE, value);
  }
  explicit __Map_string_Stats_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Map_string_Stats_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Map_string_Stats_Entry>(end);
    fbb_.Required(o, __Map_string_Stats_Entry::VT_KEY);
    return o;
  }
};

inline ::flatbuffers::Offset<__Map_string_Stats_Entry> Create__Map_string_Stats_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<MapSetTest::Stats> value = 0) {
  __Map_string_Stats_EntryBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<__Map_string_Stats_Entry> Create__Map_string_Stats_EntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    ::flatbuffers::Offset<MapSetTest::Stats> value = 0) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return MapSetTest::Create__Map_string_Stats_Entry(
      _fbb,
      key__,
      value);
}

::flatbuffers::Offset<__Map_string_Stats_Entry> Create__Map_string_Stats_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_Stats_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Set_string_EntryT : public ::flatbuffers::NativeTable {
  typedef __Set_string_Entry TableType;
  std::string key{};
};

struct __Set_string_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Set_string_EntryT NativeTableType;
  typedef __Set_string_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Set_string_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  ::flatbuffers::String *mutable_key() {
    return GetPointer<::flatbuffers::String *>(VT_KEY);
  }
  bool KeyCompareLessThan(const __Set_string_Entry * const o) const {
    return *key() < *o->key();
  }
  int KeyCompareWithValue(const char *_key) const {
    return strcmp(key()->c_str(), _key);
  }
  template<typename StringType>
  int KeyCompareWithValue(const StringType& _key) const {
    if (key()->c_str() < _key) return -1;
    if (_key < key()->c_str()) return 1;
    return 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           verifier.EndTable();
  }
  __Set_string_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Set_string_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Set_string_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_string_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Set_string_EntryBuilder {
  typedef __Set_string_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(__Set_string_Entry::VT_KEY, key);
  }
  explicit __Set_string_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Set_string_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Set_string_Entry>(end);
    fbb_.Required(o, __Set_string_Entry::VT_KEY);
    return o;
  }
};

inline ::flatbuffers::Offset<__Set_string_Entry> Create__Set_string_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0) {
  __Set_string_EntryBuilder builder_(_fbb);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<__Set_string_Entry> Create__Set_string_EntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return MapSetTest::Create__Set_string_Entry(
      _fbb,
      key__);
}

::flatbuffers::Offset<__Set_string_Entry> Create__Set_string_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_string_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct __Set_int_EntryT : public ::flatbuffers::NativeTable {
  typedef __Set_int_Entry TableType;
  int32_t key = 0;
};

struct __Set_int_Entry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef __Set_int_EntryT NativeTableType;
  typedef __Set_int_EntryBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return __Set_int_EntryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4
  };
  int32_t key() const {
    return GetField<int32_t>(VT_KEY, 0);
  }
  bool mutate_key(int32_t _key = 0) {
    return SetField<int32_t>(VT_KEY, _key, 0);
  }
  bool KeyCompareLessThan(const __Set_int_Entry * const o) const {
    return key() < o->key();
  }
  int KeyCompareWithValue(int32_t _key) const {
    return static_cast<int>(key() > _key) - static_cast<int>(key() < _key);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_KEY, 4) &&
           verifier.EndTable();
  }
  __Set_int_EntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(__Set_int_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<__Set_int_Entry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_int_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct __Set_int_EntryBuilder {
  typedef __Set_int_Entry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(int32_t key) {
    fbb_.AddElement<int32_t>(__Set_int_Entry::VT_KEY, key, 0);
  }
  explicit __Set_int_EntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<__Set_int_Entry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<__Set_int_Entry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<__Set_int_Entry> Create__Set_int_Entry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t key = 0) {
  __Set_int_EntryBuilder builder_(_fbb);
  builder_.add_key(key);
  return builder_.Finish();
}

::flatbuffers::Offset<__Set_int_Entry> Create__Set_int_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_int_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AnotherConfigT : public ::flatbuffers::NativeTable {
  typedef AnotherConfig TableType;
  std::unordered_map<std::string, int32_t> overrides{};
  std::unordered_set<std::string> labels{};
  AnotherConfigT() = default;
  AnotherConfigT(const AnotherConfigT &o);
  AnotherConfigT(AnotherConfigT&&) FLATBUFFERS_NOEXCEPT = default;
  AnotherConfigT &operator=(AnotherConfigT o) FLATBUFFERS_NOEXCEPT;
};

struct AnotherConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnotherConfigT NativeTableType;
  typedef AnotherConfigBuilder Builder;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AnotherConfigTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OVERRIDES = 4,
    VT_LABELS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *overrides() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *>(VT_OVERRIDES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *mutable_overrides() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *>(VT_OVERRIDES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *labels() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *>(VT_LABELS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *mutable_labels() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *>(VT_LABELS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OVERRIDES) &&
           verifier.VerifyVector(overrides()) &&
           verifier.VerifyVectorOfTables(overrides()) &&
           VerifyOffset(verifier, VT_LABELS) &&
           verifier.VerifyVector(labels()) &&
           verifier.VerifyVectorOfTables(labels()) &&
           verifier.EndTable();
  }
  AnotherConfigT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AnotherConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AnotherConfig> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AnotherConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AnotherConfigBuilder {
  typedef AnotherConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_overrides(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>>> overrides) {
    fbb_.AddOffset(AnotherConfig::VT_OVERRIDES, overrides);
  }
  void add_labels(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>>> labels) {
    fbb_.AddOffset(AnotherConfig::VT_LABELS, labels);
  }
  explicit AnotherConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnotherConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnotherConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnotherConfig> CreateAnotherConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>>> overrides = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>>> labels = 0) {
  AnotherConfigBuilder builder_(_fbb);
  builder_.add_labels(labels);
  builder_.add_overrides(overrides);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnotherConfig> CreateAnotherConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> *overrides = nullptr,
    std::vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> *labels = nullptr) {
  auto overrides__ = overrides ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Map_string_int_Entry>(overrides) : 0;
  auto labels__ = labels ? _fbb.CreateVectorOfSortedTables<MapSetTest::__Set_string_Entry>(labels) : 0;
  return MapSetTest::CreateAnotherConfig(
      _fbb,
      overrides__,
      labels__);
}

::flatbuffers::Offset<AnotherConfig> CreateAnotherConfig(::flatbuffers::FlatBufferBuilder &_fbb, const AnotherConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const StatsT &lhs, const StatsT &rhs) {
  return
      (lhs.hp == rhs.hp) &&
      (lhs.strength == rhs.strength);
}

inline bool operator!=(const StatsT &lhs, const StatsT &rhs) {
    return !(lhs == rhs);
}


inline StatsT *Stats::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<StatsT>(new StatsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Stats::UnPackTo(StatsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = hp(); _o->hp = _e; }
  { auto _e = strength(); _o->strength = _e; }
}

inline ::flatbuffers::Offset<Stats> CreateStats(::flatbuffers::FlatBufferBuilder &_fbb, const StatsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Stats::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Stats> Stats::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const StatsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const StatsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _hp = _o->hp;
  auto _strength = _o->strength;
  return MapSetTest::CreateStats(
      _fbb,
      _hp,
      _strength);
}


inline bool operator==(const ConfigT &lhs, const ConfigT &rhs) {
  return
      (lhs.settings == rhs.settings) &&
      (lhs.id_to_name == rhs.id_to_name) &&
      (lhs.color_scores == rhs.color_scores) &&
      (lhs.profiles == rhs.profiles) &&
      (lhs.tags == rhs.tags) &&
      (lhs.active_ids == rhs.active_ids);
}

inline bool operator!=(const ConfigT &lhs, const ConfigT &rhs) {
    return !(lhs == rhs);
}


inline ConfigT::ConfigT(const ConfigT &o)
      : settings(o.settings),
        id_to_name(o.id_to_name),
        color_scores(o.color_scores),
        tags(o.tags),
        active_ids(o.active_ids) {
  for (const auto &_kv : o.profiles) { profiles[_kv.first] = _kv.second ? std::unique_ptr<MapSetTest::StatsT>(new MapSetTest::StatsT(*_kv.second)) : nullptr; }
}

inline ConfigT &ConfigT::operator=(ConfigT o) FLATBUFFERS_NOEXCEPT {
  std::swap(settings, o.settings);
  std::swap(id_to_name, o.id_to_name);
  std::swap(color_scores, o.color_scores);
  std::swap(profiles, o.profiles);
  std::swap(tags, o.tags);
  std::swap(active_ids, o.active_ids);
  return *this;
}

inline ConfigT *Config::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ConfigT>(new ConfigT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Config::UnPackTo(ConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = settings(); if (_e) { _o->settings.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->settings[_e->Get(_i)->key()->str()] = _e->Get(_i)->value(); } } }
  { auto _e = id_to_name(); if (_e) { _o->id_to_name.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->id_to_name[_e->Get(_i)->key()] = _e->Get(_i)->value() ? _e->Get(_i)->value()->str() : ""; } } }
  { auto _e = color_scores(); if (_e) { _o->color_scores.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->color_scores[static_cast<MapSetTest::Color>(_e->Get(_i)->key())] = _e->Get(_i)->value(); } } }
  { auto _e = profiles(); if (_e) { _o->profiles.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->profiles[_e->Get(_i)->key()->str()] = std::unique_ptr<MapSetTest::StatsT>(_e->Get(_i)->value() ? _e->Get(_i)->value()->UnPack(_resolver) : nullptr); } } }
  { auto _e = tags(); if (_e) { _o->tags.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->tags.insert(_e->Get(_i)->key()->str()); } } }
  { auto _e = active_ids(); if (_e) { _o->active_ids.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->active_ids.insert(_e->Get(_i)->key()); } } }
}

inline ::flatbuffers::Offset<Config> CreateConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Config::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Config> Config::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConfigT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _settings = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Map_string_int_EntryT> _entries; _entries.reserve(_o->settings.size()); for (const auto& _kv : _o->settings) { MapSetTest::__Map_string_int_EntryT _entry; _entry.key = _kv.first; _entry.value = _kv.second; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Map_string_int_EntryT& a, const MapSetTest::__Map_string_int_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Map_string_int_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _id_to_name = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Map_uint_string_EntryT> _entries; _entries.reserve(_o->id_to_name.size()); for (const auto& _kv : _o->id_to_name) { MapSetTest::__Map_uint_string_EntryT _entry; _entry.key = _kv.first; _entry.value = _kv.second; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Map_uint_string_EntryT& a, const MapSetTest::__Map_uint_string_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Map_uint_string_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Map_uint_string_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _color_scores = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Map_Color_float_EntryT> _entries; _entries.reserve(_o->color_scores.size()); for (const auto& _kv : _o->color_scores) { MapSetTest::__Map_Color_float_EntryT _entry; _entry.key = _kv.first; _entry.value = _kv.second; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Map_Color_float_EntryT& a, const MapSetTest::__Map_Color_float_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Map_Color_float_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Map_Color_float_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _profiles = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Map_string_Stats_EntryT> _entries; _entries.reserve(_o->profiles.size()); for (const auto& _kv : _o->profiles) { MapSetTest::__Map_string_Stats_EntryT _entry; _entry.key = _kv.first; _entry.value = _kv.second ? std::unique_ptr<MapSetTest::StatsT>(new MapSetTest::StatsT(*_kv.second)) : nullptr; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Map_string_Stats_EntryT& a, const MapSetTest::__Map_string_Stats_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_Stats_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Map_string_Stats_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _tags = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Set_string_EntryT> _entries; _entries.reserve(_o->tags.size()); for (const auto& _k : _o->tags) { MapSetTest::__Set_string_EntryT _entry; _entry.key = _k; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Set_string_EntryT& a, const MapSetTest::__Set_string_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Set_string_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _active_ids = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Set_int_EntryT> _entries; _entries.reserve(_o->active_ids.size()); for (const auto& _k : _o->active_ids) { MapSetTest::__Set_int_EntryT _entry; _entry.key = _k; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Set_int_EntryT& a, const MapSetTest::__Set_int_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Set_int_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Set_int_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  return MapSetTest::CreateConfig(
      _fbb,
      _settings,
      _id_to_name,
      _color_scores,
      _profiles,
      _tags,
      _active_ids);
}


inline bool operator==(const __Map_string_int_EntryT &lhs, const __Map_string_int_EntryT &rhs) {
  return
      (lhs.key == rhs.key) &&
      (lhs.value == rhs.value);
}

inline bool operator!=(const __Map_string_int_EntryT &lhs, const __Map_string_int_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Map_string_int_EntryT *__Map_string_int_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Map_string_int_EntryT>(new __Map_string_int_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Map_string_int_Entry::UnPackTo(__Map_string_int_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<__Map_string_int_Entry> Create__Map_string_int_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_int_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Map_string_int_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Map_string_int_Entry> __Map_string_int_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_int_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Map_string_int_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _fbb.CreateString(_o->key);
  auto _value = _o->value;
  return MapSetTest::Create__Map_string_int_Entry(
      _fbb,
      _key,
      _value);
}


inline bool operator==(const __Map_uint_string_EntryT &lhs, const __Map_uint_string_EntryT &rhs) {
  return
      (lhs.key == rhs.key) &&
      (lhs.value == rhs.value);
}

inline bool operator!=(const __Map_uint_string_EntryT &lhs, const __Map_uint_string_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Map_uint_string_EntryT *__Map_uint_string_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Map_uint_string_EntryT>(new __Map_uint_string_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Map_uint_string_Entry::UnPackTo(__Map_uint_string_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); _o->key = _e; }
  { auto _e = value(); if (_e) _o->value = _e->str(); }
}

inline ::flatbuffers::Offset<__Map_uint_string_Entry> Create__Map_uint_string_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_uint_string_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Map_uint_string_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Map_uint_string_Entry> __Map_uint_string_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_uint_string_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Map_uint_string_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key;
  auto _value = _o->value.empty() ? 0 : _fbb.CreateString(_o->value);
  return MapSetTest::Create__Map_uint_string_Entry(
      _fbb,
      _key,
      _value);
}


inline bool operator==(const __Map_Color_float_EntryT &lhs, const __Map_Color_float_EntryT &rhs) {
  return
      (lhs.key == rhs.key) &&
      (lhs.value == rhs.value);
}

inline bool operator!=(const __Map_Color_float_EntryT &lhs, const __Map_Color_float_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Map_Color_float_EntryT *__Map_Color_float_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Map_Color_float_EntryT>(new __Map_Color_float_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Map_Color_float_Entry::UnPackTo(__Map_Color_float_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); _o->key = _e; }
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<__Map_Color_float_Entry> Create__Map_Color_float_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_Color_float_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Map_Color_float_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Map_Color_float_Entry> __Map_Color_float_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_Color_float_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Map_Color_float_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key;
  auto _value = _o->value;
  return MapSetTest::Create__Map_Color_float_Entry(
      _fbb,
      _key,
      _value);
}


inline bool operator==(const __Map_string_Stats_EntryT &lhs, const __Map_string_Stats_EntryT &rhs) {
  return
      (lhs.key == rhs.key) &&
      ((lhs.value == rhs.value) || (lhs.value && rhs.value && *lhs.value == *rhs.value));
}

inline bool operator!=(const __Map_string_Stats_EntryT &lhs, const __Map_string_Stats_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Map_string_Stats_EntryT::__Map_string_Stats_EntryT(const __Map_string_Stats_EntryT &o)
      : key(o.key),
        value((o.value) ? new MapSetTest::StatsT(*o.value) : nullptr) {
}

inline __Map_string_Stats_EntryT &__Map_string_Stats_EntryT::operator=(__Map_string_Stats_EntryT o) FLATBUFFERS_NOEXCEPT {
  std::swap(key, o.key);
  std::swap(value, o.value);
  return *this;
}

inline __Map_string_Stats_EntryT *__Map_string_Stats_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Map_string_Stats_EntryT>(new __Map_string_Stats_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Map_string_Stats_Entry::UnPackTo(__Map_string_Stats_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = value(); if (_e) { if(_o->value) { _e->UnPackTo(_o->value.get(), _resolver); } else { _o->value = std::unique_ptr<MapSetTest::StatsT>(_e->UnPack(_resolver)); } } else if (_o->value) { _o->value.reset(); } }
}

inline ::flatbuffers::Offset<__Map_string_Stats_Entry> Create__Map_string_Stats_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_Stats_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Map_string_Stats_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Map_string_Stats_Entry> __Map_string_Stats_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Map_string_Stats_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Map_string_Stats_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _fbb.CreateString(_o->key);
  auto _value = _o->value ? MapSetTest::CreateStats(_fbb, _o->value.get(), _rehasher) : 0;
  return MapSetTest::Create__Map_string_Stats_Entry(
      _fbb,
      _key,
      _value);
}


inline bool operator==(const __Set_string_EntryT &lhs, const __Set_string_EntryT &rhs) {
  return
      (lhs.key == rhs.key);
}

inline bool operator!=(const __Set_string_EntryT &lhs, const __Set_string_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Set_string_EntryT *__Set_string_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Set_string_EntryT>(new __Set_string_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Set_string_Entry::UnPackTo(__Set_string_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
}

inline ::flatbuffers::Offset<__Set_string_Entry> Create__Set_string_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_string_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Set_string_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Set_string_Entry> __Set_string_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_string_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Set_string_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _fbb.CreateString(_o->key);
  return MapSetTest::Create__Set_string_Entry(
      _fbb,
      _key);
}


inline bool operator==(const __Set_int_EntryT &lhs, const __Set_int_EntryT &rhs) {
  return
      (lhs.key == rhs.key);
}

inline bool operator!=(const __Set_int_EntryT &lhs, const __Set_int_EntryT &rhs) {
    return !(lhs == rhs);
}


inline __Set_int_EntryT *__Set_int_Entry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<__Set_int_EntryT>(new __Set_int_EntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void __Set_int_Entry::UnPackTo(__Set_int_EntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); _o->key = _e; }
}

inline ::flatbuffers::Offset<__Set_int_Entry> Create__Set_int_Entry(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_int_EntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return __Set_int_Entry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<__Set_int_Entry> __Set_int_Entry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const __Set_int_EntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const __Set_int_EntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key;
  return MapSetTest::Create__Set_int_Entry(
      _fbb,
      _key);
}


inline bool operator==(const AnotherConfigT &lhs, const AnotherConfigT &rhs) {
  return
      (lhs.overrides == rhs.overrides) &&
      (lhs.labels == rhs.labels);
}

inline bool operator!=(const AnotherConfigT &lhs, const AnotherConfigT &rhs) {
    return !(lhs == rhs);
}


inline AnotherConfigT::AnotherConfigT(const AnotherConfigT &o)
      : overrides(o.overrides),
        labels(o.labels) {
}

inline AnotherConfigT &AnotherConfigT::operator=(AnotherConfigT o) FLATBUFFERS_NOEXCEPT {
  std::swap(overrides, o.overrides);
  std::swap(labels, o.labels);
  return *this;
}

inline AnotherConfigT *AnotherConfig::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AnotherConfigT>(new AnotherConfigT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AnotherConfig::UnPackTo(AnotherConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = overrides(); if (_e) { _o->overrides.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->overrides[_e->Get(_i)->key()->str()] = _e->Get(_i)->value(); } } }
  { auto _e = labels(); if (_e) { _o->labels.clear(); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->labels.insert(_e->Get(_i)->key()->str()); } } }
}

inline ::flatbuffers::Offset<AnotherConfig> CreateAnotherConfig(::flatbuffers::FlatBufferBuilder &_fbb, const AnotherConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return AnotherConfig::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AnotherConfig> AnotherConfig::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AnotherConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AnotherConfigT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _overrides = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Map_string_int_EntryT> _entries; _entries.reserve(_o->overrides.size()); for (const auto& _kv : _o->overrides) { MapSetTest::__Map_string_int_EntryT _entry; _entry.key = _kv.first; _entry.value = _kv.second; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Map_string_int_EntryT& a, const MapSetTest::__Map_string_int_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Map_string_int_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Map_string_int_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  auto _labels = [&_fbb, &_o, &_rehasher]() { std::vector<MapSetTest::__Set_string_EntryT> _entries; _entries.reserve(_o->labels.size()); for (const auto& _k : _o->labels) { MapSetTest::__Set_string_EntryT _entry; _entry.key = _k; _entries.push_back(std::move(_entry)); } std::sort(_entries.begin(), _entries.end(), [](const MapSetTest::__Set_string_EntryT& a, const MapSetTest::__Set_string_EntryT& b) { return a.key < b.key; }); std::vector<::flatbuffers::Offset<MapSetTest::__Set_string_Entry>> _v; _v.reserve(_entries.size()); for (const auto& _e : _entries) { _v.push_back(Create__Set_string_Entry(_fbb, &_e, _rehasher)); } return _fbb.CreateVector(_v); }();
  return MapSetTest::CreateAnotherConfig(
      _fbb,
      _overrides,
      _labels);
}

inline const ::flatbuffers::TypeTable *ColorTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_CHAR, 0, 0 },
    { ::flatbuffers::ET_CHAR, 0, 0 },
    { ::flatbuffers::ET_CHAR, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MapSetTest::ColorTypeTable
  };
  static const char * const names[] = {
    "Red",
    "Green",
    "Blue"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *StatsTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const char * const names[] = {
    "hp",
    "strength"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *ConfigTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 },
    { ::flatbuffers::ET_SEQUENCE, 1, 2 },
    { ::flatbuffers::ET_SEQUENCE, 1, 3 },
    { ::flatbuffers::ET_SEQUENCE, 1, 4 },
    { ::flatbuffers::ET_SEQUENCE, 1, 5 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MapSetTest::__Map_string_int_EntryTypeTable,
    MapSetTest::__Map_uint_string_EntryTypeTable,
    MapSetTest::__Map_Color_float_EntryTypeTable,
    MapSetTest::__Map_string_Stats_EntryTypeTable,
    MapSetTest::__Set_string_EntryTypeTable,
    MapSetTest::__Set_int_EntryTypeTable
  };
  static const char * const names[] = {
    "settings",
    "id_to_name",
    "color_scores",
    "profiles",
    "tags",
    "active_ids"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 6, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Map_string_int_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 }
  };
  static const char * const names[] = {
    "key",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Map_uint_string_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UINT, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "key",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Map_Color_float_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_CHAR, 0, 0 },
    { ::flatbuffers::ET_FLOAT, 0, -1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MapSetTest::ColorTypeTable
  };
  static const char * const names[] = {
    "key",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Map_string_Stats_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MapSetTest::StatsTypeTable
  };
  static const char * const names[] = {
    "key",
    "value"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Set_string_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "key"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *__Set_int_EntryTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 }
  };
  static const char * const names[] = {
    "key"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 1, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *AnotherConfigTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 1, 0 },
    { ::flatbuffers::ET_SEQUENCE, 1, 1 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MapSetTest::__Map_string_int_EntryTypeTable,
    MapSetTest::__Set_string_EntryTypeTable
  };
  static const char * const names[] = {
    "overrides",
    "labels"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const MapSetTest::Config *GetConfig(const void *buf) {
  return ::flatbuffers::GetRoot<MapSetTest::Config>(buf);
}

inline const MapSetTest::Config *GetSizePrefixedConfig(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MapSetTest::Config>(buf);
}

inline Config *GetMutableConfig(void *buf) {
  return ::flatbuffers::GetMutableRoot<Config>(buf);
}

inline MapSetTest::Config *GetMutableSizePrefixedConfig(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<MapSetTest::Config>(buf);
}

template <bool B = false>
inline bool VerifyConfigBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<MapSetTest::Config>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedConfigBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<MapSetTest::Config>(nullptr);
}

inline void FinishConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MapSetTest::Config> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MapSetTest::Config> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<MapSetTest::ConfigT> UnPackConfig(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MapSetTest::ConfigT>(GetConfig(buf)->UnPack(res));
}

inline std::unique_ptr<MapSetTest::ConfigT> UnPackSizePrefixedConfig(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<MapSetTest::ConfigT>(GetSizePrefixedConfig(buf)->UnPack(res));
}

}  // namespace MapSetTest

#endif  // FLATBUFFERS_GENERATED_MAPSETTEST_MAPSETTEST_H_
